### ISSUE TITLE
Docker Python error [Solved]

### ISSUE THREAD

**Issue by LucHermkens** [DewGew/Domoticz-Google-Assistant#135]
**Describe the bug:**  
Python error when trying to run the latest Docker image.

**Expected behavior:**  
Actually working.

**Logs:**
```
domoticzg     | First run, checking for any requirements...
domoticzg     | Installing all APK requirements...
domoticzg     | fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
domoticzg     | (1/26) Installing binutils (2.30-r6)
domoticzg     | (2/26) Installing libmagic (5.32-r2)
domoticzg     | (3/26) Installing file (5.32-r2)
domoticzg     | (4/26) Installing gmp (6.1.2-r1)
domoticzg     | (5/26) Installing isl (0.18-r0)
domoticzg     | (6/26) Installing libgomp (6.4.0-r9)
domoticzg     | (7/26) Installing libatomic (6.4.0-r9)
domoticzg     | (8/26) Installing pkgconf (1.5.3-r0)
domoticzg     | (9/26) Installing libgcc (6.4.0-r9)
domoticzg     | (10/26) Installing mpfr3 (3.1.5-r1)
domoticzg     | (11/26) Installing mpc1 (1.0.3-r1)
domoticzg     | (12/26) Installing libstdc++ (6.4.0-r9)
domoticzg     | (13/26) Installing gcc (6.4.0-r9)
domoticzg     | (14/26) Installing musl-dev (1.1.19-r11)
domoticzg     | (15/26) Installing libc-dev (0.7.1-r0)
domoticzg     | (16/26) Installing g++ (6.4.0-r9)
domoticzg     | (17/26) Installing make (4.2.1-r2)
domoticzg     | (18/26) Installing fortify-headers (0.9-r0)
domoticzg     | (19/26) Installing build-base (0.5-r1)
domoticzg     | (20/26) Installing nghttp2-libs (1.39.2-r0)
domoticzg     | (21/26) Installing libssh2 (1.9.0-r1)
domoticzg     | (22/26) Installing libcurl (7.61.1-r3)
domoticzg     | (23/26) Installing pcre2 (10.31-r0)
domoticzg     | (24/26) Installing git (2.18.2-r0)
domoticzg     | (25/26) Installing libc6-compat (1.1.19-r11)
domoticzg     | (26/26) Installing linux-headers (4.4.6-r2)
domoticzg     | Executing busybox-1.28.4-r3.trigger
domoticzg     | OK: 198 MiB in 62 packages
domoticzg     | Pip requirements file detected!
domoticzg     | Upgrading Pip...
domoticzg     | Collecting pip
domoticzg     |   Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
domoticzg     | Installing collected packages: pip
domoticzg     |   Found existing installation: pip 19.0.3
domoticzg     |     Uninstalling pip-19.0.3:
domoticzg     |       Successfully uninstalled pip-19.0.3
domoticzg     | Successfully installed pip-20.0.2
domoticzg     | Installing all Pip requirements...
domoticzg     | Collecting certifi>=2019.9.11
domoticzg     |   Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
domoticzg     | Collecting chardet>=3.0.4
domoticzg     |   Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
domoticzg     | Collecting future>=0.18.2
domoticzg     |   Downloading future-0.18.2.tar.gz (829 kB)
domoticzg     | Collecting idna>=2.8
domoticzg     |   Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
domoticzg     | Collecting PyYAML>=5.1.2
domoticzg     |   Downloading PyYAML-5.3.tar.gz (268 kB)
domoticzg     | Collecting requests>=2.22.0
domoticzg     |   Downloading requests-2.23.0-py2.py3-none-any.whl (58 kB)
domoticzg     | Collecting urllib3>=1.25.7
domoticzg     |   Downloading urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
domoticzg     | Collecting GitPython>=3.0.5
domoticzg     |   Downloading GitPython-3.1.0-py3-none-any.whl (450 kB)
domoticzg     | Collecting google-auth>=1.8.1
domoticzg     |   Downloading google_auth-1.11.2-py2.py3-none-any.whl (76 kB)
domoticzg     | Collecting gitdb<5,>=4.0.1
domoticzg     |   Downloading gitdb-4.0.2-py3-none-any.whl (63 kB)
domoticzg     | Collecting pyasn1-modules>=0.2.1
domoticzg     |   Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
domoticzg     | Collecting rsa<4.1,>=3.1.4
domoticzg     |   Downloading rsa-4.0-py2.py3-none-any.whl (38 kB)
domoticzg     | Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/pyenv/versions/3.7.3/lib/python3.7/site-packages (from google-auth>=1.8.1->-r /requirements.txt (line 9)) (40.8.0)
domoticzg     | Collecting cachetools<5.0,>=2.0.0
domoticzg     |   Downloading cachetools-4.0.0-py3-none-any.whl (10 kB)
domoticzg     | Collecting six>=1.9.0
domoticzg     |   Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
domoticzg     | Collecting smmap<4,>=3.0.1
domoticzg     |   Downloading smmap-3.0.1-py2.py3-none-any.whl (25 kB)
domoticzg     | Collecting pyasn1<0.5.0,>=0.4.6
domoticzg     |   Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
domoticzg     | Installing collected packages: certifi, chardet, future, idna, PyYAML, urllib3, requests, smmap, gitdb, GitPython, pyasn1, pyasn1-modules, rsa, cachetools, six, google-auth
domoticzg     |     Running setup.py install for future: started
domoticzg     |     Running setup.py install for future: finished with status 'done'
domoticzg     |     Running setup.py install for PyYAML: started
domoticzg     |     Running setup.py install for PyYAML: finished with status 'done'
domoticzg     | Successfully installed GitPython-3.1.0 PyYAML-5.3 cachetools-4.0.0 certifi-2019.11.28 chardet-3.0.4 future-0.18.2 gitdb-4.0.2 google-auth-1.11.2 idna-2.9 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.23.0 rsa-4.0 six-1.14.0 smmap-3.0.1 urllib3-1.25.8
domoticzg     | fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
domoticzg     | (1/26) Purging build-base (0.5-r1)
domoticzg     | (2/26) Purging file (5.32-r2)
domoticzg     | (3/26) Purging g++ (6.4.0-r9)
domoticzg     | (4/26) Purging gcc (6.4.0-r9)
domoticzg     | (5/26) Purging binutils (2.30-r6)
domoticzg     | (6/26) Purging libatomic (6.4.0-r9)
domoticzg     | (7/26) Purging libgomp (6.4.0-r9)
domoticzg     | (8/26) Purging libstdc++ (6.4.0-r9)
domoticzg     | (9/26) Purging make (4.2.1-r2)
domoticzg     | (10/26) Purging libc-dev (0.7.1-r0)
domoticzg     | (11/26) Purging musl-dev (1.1.19-r11)
domoticzg     | (12/26) Purging fortify-headers (0.9-r0)
domoticzg     | (13/26) Purging git (2.18.2-r0)
domoticzg     | (14/26) Purging libc6-compat (1.1.19-r11)
domoticzg     | (15/26) Purging linux-headers (4.4.6-r2)
domoticzg     | (16/26) Purging libmagic (5.32-r2)
domoticzg     | (17/26) Purging mpc1 (1.0.3-r1)
domoticzg     | (18/26) Purging mpfr3 (3.1.5-r1)
domoticzg     | (19/26) Purging isl (0.18-r0)
domoticzg     | (20/26) Purging gmp (6.1.2-r1)
domoticzg     | (21/26) Purging pkgconf (1.5.3-r0)
domoticzg     | (22/26) Purging libgcc (6.4.0-r9)
domoticzg     | (23/26) Purging libcurl (7.61.1-r3)
domoticzg     | (24/26) Purging nghttp2-libs (1.39.2-r0)
domoticzg     | (25/26) Purging libssh2 (1.9.0-r1)
domoticzg     | (26/26) Purging pcre2 (10.31-r0)
domoticzg     | Executing busybox-1.28.4-r3.trigger
domoticzg     | OK: 18 MiB in 36 packages
domoticzg     | Installing APK requirements...
domoticzg     | fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
domoticzg     | OK: 18 MiB in 36 packages
domoticzg     | Loading configuration...
domoticzg     | Traceback (most recent call last):
domoticzg     |   File "/__main__.py", line 4, in <module>
domoticzg     |     from server import *
domoticzg     |   File "/server.py", line 7, in <module>
domoticzg     |     from smarthome import *
domoticzg     |   File "/smarthome.py", line 14, in <module>
domoticzg     |     import trait
domoticzg     |   File "/trait.py", line 14, in <module>
domoticzg     |     from helpers import SmartHomeError, configuration, logger, tempConvert
domoticzg     |   File "/helpers.py", line 121, in <module>
domoticzg     |     configuration['ClientID'] = 'sampleClientId'
domoticzg     | TypeError: 'str' object does not support item assignment
domoticzg exited with code 1
```

**Desktop (please complete the following information):**
 - Ubuntu version: 18.04.4 LTS
 - Docker version: 19.03.6, build 369ce74a3c
 - Domoticz version: 4.11777
 - Dzga docker version: latest

**Comment by DewGew** [comment]
Did you follow wiki?
https://github.com/DewGew/Domoticz-Google-Assistant/wiki/DZGA-with-Docker

**Comment by LucHermkens** [comment]
@DewGew Yes I did. The thing is, the `docker` branch doesn't even seem to have a `Dockerfile`. I've also tried to manually add it to my own docker-compose file like this:

```yaml
  domoticzg:
    container_name: domoticzg
    image: dewgew/domoticz-google-assistant:latest
    restart: unless-stopped
    hostname: domoticzg
    ports:
      - 3030:3030
    volumes:
      - /services/domoticzg/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - bridge
```

Neither are working.

**Comment by DewGew** [comment]
Try: 
`cd /home/${USER}`
`git clone https://github.com/DewGew/Domoticz-Google-Assistant`
`docker-compose -f /home/${USER}/Domoticz-Google-Assistant/docker-compose.yaml up -d`

**Comment by LucHermkens** [comment]
Why are you closing this issue? It isn't resolved yet. I've tried those commands, they're just from the wiki. I'm telling you, there's an error with Python.

```domoticzg     | Traceback (most recent call last):
domoticzg     |   File "/__main__.py", line 4, in <module>
domoticzg     |     from server import *
domoticzg     |   File "/server.py", line 7, in <module>
domoticzg     |     from smarthome import *
domoticzg     |   File "/smarthome.py", line 14, in <module>
domoticzg     |     import trait
domoticzg     |   File "/trait.py", line 14, in <module>
domoticzg     |     from helpers import SmartHomeError, configuration, logger, tempConvert
domoticzg     |   File "/helpers.py", line 121, in <module>
domoticzg     |     configuration['ClientID'] = 'sampleClientId'
domoticzg     | TypeError: 'str' object does not support item assignment```

**Comment by DewGew** [comment]
docker-compose is updated.
This command work for me on ubuntu:

```
cd /home/${USER}
git clone https://github.com/DewGew/Domoticz-Google-Assistant -b docker --single-branch
docker-compose -f /home/${USER}/Domoticz-Google-Assistant/docker-compose.yaml up -d
```
Make sure you remove old versions first:
```
cd /home/${USER}
sudo rm -r Domoticz-Google-Assistant
```

**Comment by DewGew** [comment]
According to your log.` /home/${USER}/Domoticz-Google-Assistant/config/defult_config` is missing.

**Comment by rezzalex** [comment]
Hello.
I am experiencing the exact same issue.
I didn't understand how last comments were helping to resolve the issue. Thanks for your help
