### ISSUE TITLE
Cannot install on Debian 10.7 "SyntaxError"

### ISSUE THREAD

**Issue by Catfriend1** [DewGew/Domoticz-Google-Assistant#242]
Hi,

When running

> python3 Domoticz-Google-Assistant

after a fresh installation, it fails with:

<details>
```
Loading configuration...
No config.yaml found...
Loading default configuration...
Create config.yaml...
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Domoticz-Google-Assistant/__main__.py", line 4, in <module>
    from server import *
  File "Domoticz-Google-Assistant/server.py", line 8, in <module>
    from smarthome import *
  File "Domoticz-Google-Assistant/smarthome.py", line 16, in <module>
    from auth import *
  File "Domoticz-Google-Assistant/auth.py", line 5, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3219, in _initialize_master_working_set
    for dist in working_set
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3219, in <genexpr>
    for dist in working_set
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2726, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2252, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2185, in _handle_ns
    loader.load_module(packageName)
  File "/usr/local/lib/python3.7/dist-packages/pygoogle/google.py", line 118
    %(__credits__)s""" % globals()
                     ^
SyntaxError: invalid syntax
```
</details>
I've tried the release from Nov 28 2020 and BETA, both fail with that error. systemctl status also shows the failed service. I'm running as root.

Thank you for the help.

Kind regards
Catfriend1

Install Log:
<details>
```
bash <(curl -s https://raw.githubusercontent.com/DewGew/dzga-installer/master/install.sh)
/dev/fd/63: Zeile 21: cd: /home/root/: Datei oder Verzeichnis nicht gefunden
*--------------------**---------------------*
Install Domoticz-Google-Assistant
---------------------------------------------
*Note : Domoticz-Google-Assistant is free
*for personal use.
---------------------------------------------
Install the Development branch?
(y)es or (N)o? Default : No
y
Getting the Development Branch
Klone nach 'Domoticz-Google-Assistant' ...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 3815 (delta 12), reused 16 (delta 4), pack-reused 3777
Empfange Objekte: 100% (3815/3815), 5.65 MiB | 6.81 MiB/s, Fertig.
Löse Unterschiede auf: 100% (2133/2133), Fertig.

 Updating your system...

OK:1 http://security.debian.org/debian-security buster/updates InRelease
OK:2 http://deb.debian.org/debian buster InRelease
OK:3 http://deb.debian.org/debian buster-updates InRelease
OK:4 http://apt.syncthing.net syncthing InRelease
Paketlisten werden gelesen... Fertig
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
libffi-dev ist schon die neueste Version (3.2.1-9).
python3-pip ist schon die neueste Version (18.1-5).
python3 ist schon die neueste Version (3.7.3-1).
python3-dev ist schon die neueste Version (3.7.3-1).
python3-venv ist schon die neueste Version (3.7.3-1).
libssl-dev ist schon die neueste Version (1.1.1d-0+deb10u4).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
./Domoticz-Google-Assistant/scripts/install.sh: Zeile 33: cd: /home/root/: Datei oder Verzeichnis nicht gefunden

 Installing dzga.service...


 Starting Domoticz Google Assistant...

  Login to Domoticz Google Assistant Server UI at: http://ip.address:3030/settings
  Default username is admin and default password is admin
  or
  Goto Domoticz-Google-Assistant folder and Edit config.yaml and then
  restart dzga.server e.g 'sudo systemctl restart dzga'

*-----------------------------------*
```
</details>

**Comment by Catfriend1** [comment]
... and the systemd file references /root/Domoticz-Google-Assistant/env/bin/python3 which does not exist!

**Comment by Catfriend1** [comment]
Ok, I could fix it by running

> pip3 install idna==3
> pip3 install idna==3

and then re-run the installed bash of dzga.

Seems like the problem was idna v3.1 which got uninstalled by the above commands. dzga wants idna 3.0.
