### ISSUE TITLE
DZGA won't start anymore after rasbian upgrade to bullseye

### ISSUE THREAD

**Issue by harolds** [DewGew/Domoticz-Google-Assistant#281]
After upgrading ubuntu on my raspberry to bullseye dzga no longer starts.

(env) pi@domoticz:~ $ python3 Domoticz-Google-Assistant
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/Domoticz-Google-Assistant/__main__.py", line 4, in <module>
    from server import *
  File "/home/pi/Domoticz-Google-Assistant/server.py", line 6, in <module>
    from helpers import FILE_DIR
  File "/home/pi/Domoticz-Google-Assistant/helpers.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by harolds** [comment]
Sorry I fixed it.

I needed to replace cd /etc/systemd/system/dzga.service with the one from this site.
Now it is starting again ;-)
