### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by deejayd203** [DewGew/Domoticz-Google-Assistant#38]
for path,value in {**oauthGetMappings, **smarthomeGetMappings}.items():
                        ^
SyntaxError: invalid syntax

am i doing something wrong ?

**Comment by DewGew** [comment]
I haven't seen that error. What python version do you use?

**Comment by deejayd203** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 153, in _run_module_as_main
    mod_name, mod_spec, code = _get_main_module_details()
  File "/usr/lib/python3.4/runpy.py", line 196, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/lib/python3.4/runpy.py", line 126, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "Domoticz-Google-Assistant/__main__.py", line 32
    for path,value in {**oauthGetMappings, **smarthomeGetMappings}.items():

i tryed installing newer versions of python but it still says 3.4
any help?

Thx

**Comment by deejayd203** [comment]
usr/lib $ python
python             python3/           python3.6          python3.7m-config
python-config      python3-config     python3.6-config   python3m
python2            python3.4/         python3.6m         python3m-config
python2-config     python3.4-config   python3.6m-config
python2.7/         python3.4m         python3.7
python2.7-config   python3.4m-config  python3.7m

**Comment by deejayd203** [comment]
python3 Domoticz-Google-Assistant/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Domoticz-Google-Assistant/__main__.py", line 4, in <module>
    from server import *
  File "Domoticz-Google-Assistant/server.py", line 6, in <module>
    from smarthome import *
  File "Domoticz-Google-Assistant/smarthome.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by deejayd203** [comment]
good news and bad news i fixed those problems but got a new one

192.168.1.1 - - [17/Oct/2019 20:08:27] code 400, message Bad request version

**Comment by deejayd203** [comment]
can you help me? 
if i http to it it works but i need to http://192.168.1.x:3030/sync then i get an login screen
if i https i get an code 400

**Comment by DewGew** [comment]
Check your settings in Actions on Google. Try start test again

**Comment by deejayd203** [comment]
my previous post was for testing locally is that does not work i suppose the actions centre is another prob
i even made a new pi to test it on am i missing something

**Comment by DewGew** [comment]
Server need à secure connection to Google cloud to do that i use my synology as reverse  proxy. There is for sure other ways to do this.

**Comment by deejayd203** [comment]
i am trying it with nginx but atm no luck :(

**Comment by deejayd203** [comment]
it worked :) there was trouble with my proximus modem it did not passtrough 80 and 443
Thanks for the great program ;)

**Comment by DewGew** [comment]
Great 👍
